name: Test Genisys Install

on:
  workflow_dispatch:
  push:

jobs:
  test-install:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install pipx and Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        pipx install poetry

    - name: Set up Python with Poetry's Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y iptables-persistent netfilter-persistent vsftpd dnsmasq

    - name: Install Dependencies
      run: |
        sudo $(which poetry) install

    - name: Test Install Command with Sudo
      run: sudo $(which poetry) run genisys install --file tests/scripts/tests/default/data/test_config.yaml --root temp_directory

    - name: Display Installed Genisys Config
      run: ls temp_directory
