name: Test Genisys Install

on:
  workflow_dispatch:
  push:

jobs:
  test-install:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install pipx and Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        pipx install poetry

    - name: Set up Python with Poetry's Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y iptables-persistent netfilter-persistent openvswitch-switch dnsmasq vsftpd

    - name: Configure System and Services
      run: |
        sudo touch /etc/netplan/99-genisys.yaml
        sudo chmod 0644 /etc/netplan/50-cloud-init.yaml
        sudo chmod 0644 /etc/netplan/99-genisys.yaml
        echo "net.ipv4.ip_forward = 1" | sudo tee /etc/sysctl.d/99-ip-forwarding-rule.conf
        sudo sysctl -p /etc/sysctl.d/99-ip-forwarding-rule.conf
        sudo systemctl start ovsdb-server
        sudo systemctl restart dnsmasq
        sudo systemctl restart vsftpd

    - name: Install Dependencies
      run: |
        sudo $(which poetry) install

    - name: Test Install Command with Sudo
      run: sudo $(which poetry) run genisys install --file tests/scripts/tests/default/data/test_config.yaml --root temp_directory
