---
name: Test `genisys password` modifies both files
on: push
env:
  CONFIG_FILE: tests/scripts/tests/default/data/config.yaml

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: poetry

      - name: Install genisys
        run: poetry install

      - name: Setup Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Install Password
        run: |
          poetry run genisys password --file $CONFIG_FILE --password password

      - name: Check Config
        run: grep root-password $CONFIG_FILE
