---
name: Test `genisys password` modifies both files
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: poetry

      - name: Install genisys
        run: poetry install

      - name: Setup Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Install Password
        run: |
          poetry run genisys password \
            --file $GITHUB_WORKSPACE/tests/scripts/tests/default/data/config.yaml \
            --password password
